name: Build geoip.dat
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "configuration.md"
      - ".gitignore"
      - "LICENSE"
      - "**/dependabot.yml"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
          echo "MONTH=$(date +%m)" >> $GITHUB_ENV
        shell: bash
        
      - name: Build GeoIP files
        run: |
          go run ./ -c ./config.json

      - name: Generate sha256 checksum for dat files
        run: |
          cd ./output || exit 1
          for name in $(ls *.dat); do
            sha256sum ${name} > ./${name}.sha256sum
          done

      - name: Git push assets to "release" branch
        run: |
          cd output || exit 1
          git init
          git config --local user.name "needthisforctf"
          git config --local user.email "111290117+needthisforctf@users.noreply.github.com"
          git checkout -b release
          git add -A
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add geoip "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f geoip release

      - name: Release and upload assets
        run: |
          gh release create ${{ env.TAG_NAME }} -t ${{ env.RELEASE_NAME }} \
            ./output/itentis.dat \
            ./output/itentis.dat.sha256sum \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
